version: "3.9"
services:
  jndi:
    build: jndi
    ports:
      - "8888:8888"
      - "1389:1389"
  app:
    build: app
    ports:
      - "8080:8080"
    volumes:
      - tmp:/tmp
      - ./sova.yaml:/etc/sova/sova.yaml
    links:
      - jndi
    depends_on:
      - jndi
  exploit:
   build: exploit
   volumes:
     - tmp:/tmp
   depends_on:
     - app
     - jndi

volumes:
  tmp:
