[package]
authors = ["Artem Konovalov"]
name = "sova"
version = "0.1.0"

[dependencies]
lazy_static = "1.0.0"
libc = "0.2"

[lib]
crate-type = ["cdylib"]
name = "sova"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
