version: '3'
services:
  reproducer:
    build: reproducer
    environment:
      - SOVA_CONFIG=/etc/sova/sova.yaml
    volumes:
      - ./sova.yaml:/etc/sova/sova.yaml
    ports:
      - 8080:80
  attacker:
    build: attacker
