use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug)]
pub struct Record {
    cmdline: String,
    cwd: String,
    datetime: String,
    domain: String,
    hostname: String,
    egid: String,
    euid: String,
    egroup: String,
    login: String,
    pid: String,
    ppid: String,
    tty: String,
    tty_uid: String,
    tty_username: String,
    username: String,
    eusername: String,
    uid: String,
    ssh: String,
    filename: String,
    gid: String,
    group: String,
    rpname: String,
    sid: String,
    tid: String,
    tid_kernel: String,
}
